# Site settings hope it will do the job
title: Venkata R. Sundaragiri
description: 'SAP Trasnformation Specialist, AI enthusiast, Seasonal SAP Consultant, and Blogger'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
disable_landing_page: true

author:
  name: 'Venkata R Sundaragiri'
  email: sundaragiriv@gmail.com
  twitter_username: sundaragiriv
  facebook_username: 
  github_username:  sundaragiriv
  linkedin_username:  sundaragiri

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
